aws_nuke:
  version: 2.14.0

aws_vault:
  version: 5.4.4

gopass:
  version: 1.9.0

payara:
  version: 5.193.1

saml2aws:
  version: 2.26.1

terraform11:
  version: 0.11.14

terraform12:
  version: 0.12.21
