---
- name: Add asdf java plugin
  shell: bash -ilc "asdf plugin add java" # noqa 305
  register: add_plugin
  failed_when: add_plugin.rc == 1
  changed_when: add_plugin.rc == 0

- name: Install AdoptOpenJDK 8, 11 and 14 # noqa 306
  shell: |
    bash -ilc " \
    asdf latest java {{ item }} | xargs -i bash -ilc 'asdf install java {}'"
  register: install_other_java
  failed_when:
    - install_other_java.rc != 0
    - '"is already installed" not in install_other_java.stdout'
  changed_when: install_other_java.rc == 0
  loop:
    - adoptopenjdk-8
    - adoptopenjdk-11
    - adoptopenjdk-14
