---
- name: Add asdf java plugin
  shell: bash -ilc "asdf plugin add java"
  register: add_plugin
  failed_when: add_plugin.rc == 1
  changed_when: add_plugin.rc == 0

- name: Install AdoptOpenJDK 8, 11 and 14
  shell: bash -ilc "asdf install java latest:{{ item }}"
  register: install_other_java
  failed_when:
    - install_other_java.rc != 0
    - '"is already installed" not in install_other_java.stdout'
  changed_when: install_other_java.rc == 0
  loop:
    - adoptopenjdk-8
    - adoptopenjdk-11
    - adoptopenjdk-14
