---
- name: Disable automatic blank screen
  dconf:
    key: "/org/gnome/desktop/session/idle-delay"
    value: "uint32 0"

- name: Disable automatic screen lock
  dconf:
    key: "/org/gnome/desktop/screensaver/lock-enabled"
    value: "false"

- name: Hide notifications while screen is locked
  dconf:
    key: "/org/gnome/desktop/notifications/show-in-lock-screen"
    value: "false"

- name: Show date on clock
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"

- name: Show seconds on clock
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-seconds"
    value: "true"

- name: Show weekdays on calendar
  dconf:
    key: "/org/gnome/desktop/calendar/show-weekdate"
    value: "true"

- name: Move dock to bottom
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "BOTTOM"

- name: Set dock icons' size to 34
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size"
    value: "34"

- name: Enable gnome-shell extensions (available after restarting)
  dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value:
      - gnome-shell-trash-extension
      - openweather-extension@jenslody.de
      - user-theme@gnome-shell-extensions.gcampax.github.com
      - dash-to-dock@micxgx.gmail.com