---
- name: Install aws-cli
  pip:
    executable: /usr/bin/pip3
    name: awscli

- import_tasks: saml2aws.yml
  become: no

- import_tasks: aws_nuke.yml
  become: no

- import_tasks: aws_session_manager_plugin.yml
