---
- name: Download AWS Session Manager Plugin
  get_url:
    url: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb
    dest: /tmp/session-manager-plugin.deb
    mode: u+x
  become: no
