---
- name: Add Flathup repository
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  flatpak:
    name: "{{ item }}"
  with_items:
    - org.remmina.Remmina
    - us.zoom.Zoom
  become: no
