---
- name: Download Payara {{ payara.version }}
  get_url:
    url: https://s3-eu-west-1.amazonaws.com/payara.fish/Payara+Downloads/{{ payara.version }}/payara-{{ payara.version }}.zip
    dest: /tmp/payara5.zip
  become: no

- name: Unarchive Payara {{ payara.version }}
  unarchive:
    src: /tmp/payara5.zip
    dest: /opt/

- name: Add Payara {{ payara.version }} to PATH
  lineinfile:
    path: ~/.bashrc
    regexp: ^PATH=\".*\"$
    line: PATH="$HOME/.local/bin:$PATH:/opt/payara5/bin"
  become: no
