---
- name: Install Python {{ python.version }} dependencies
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
  vars:
    packages:
    - build-essential
    - zlib1g-dev
    - libncurses5-dev
    - libgdbm-dev
    - libnss3-dev
    - libssl-dev
    - libreadline-dev
    - libffi-dev

- name: Download Python {{ python.version }}
  get_url:
    url: https://www.python.org/ftp/python/{{ python.version }}/Python-{{ python.version }}.tgz
    dest: /tmp/

- name: Unarchive Python {{ python.version }}
  unarchive:
    src: /tmp/Python-{{ python.version }}.tgz
    dest: /opt/

- name: Check if Makefile already exists
  stat:
    path: /opt/Python-{{ python.version }}/Makefile
  register: makefile
  changed_when: False

- name: Configure Python {{ python.version }}
  command: ./configure --enable-optimizations --with-ensurepip=install
  args:
    chdir: /opt/Python-{{ python.version }}
  when: not makefile.stat.exists

- name: Install Python {{ python.version }}
  command: make altinstall
  args:
    chdir: /opt/Python-{{ python.version }}
  when: not makefile.stat.exists