---
- name: Download saml2aws
  get_url:
    url: https://github.com/Versent/saml2aws/releases/download/v{{ saml2aws.version }}/saml2aws_{{ saml2aws.version }}_linux_amd64.tar.gz
    dest: /tmp/

- name: Unarchive saml2aws
  unarchive:
    src: /tmp/saml2aws_{{ saml2aws.version }}_linux_amd64.tar.gz
    dest: /tmp

- name: Copy saml2aws into ~/.local/bin
  copy:
    src: /tmp/saml2aws
    dest: ~/.local/bin/
    mode: u+x
