---
- name: Download SDKMAN! installation script
  get_url:
    url: https://get.sdkman.io
    dest: /tmp/install_sdkman.sh
    mode: u+x

- name: Install SDKMAN!
  command: /tmp/install_sdkman.sh

- name: Install JDK 8 ({{ sdkman.adoptopenjdk_8.version }})
  shell: . ~/.sdkman/bin/sdkman-init.sh && sdk install java {{ sdkman.adoptopenjdk_8.version }}
  args:
    executable: /bin/bash
  register: result
  changed_when: result.rc == 0 or "is already installed" in result.stdout

- name: Install JDK 11 ({{ sdkman.adoptopenjdk_11.version }})
  shell: . ~/.sdkman/bin/sdkman-init.sh && sdk install java {{ sdkman.adoptopenjdk_11.version }}
  args:
    executable: /bin/bash
  register: result
  changed_when: result.rc == 0 or "is already installed" in result.stdout

- name: Set up default JDK to 11 ({{ sdkman.adoptopenjdk_11.version }})
  shell: . ~/.sdkman/bin/sdkman-init.sh && sdk use java {{ sdkman.adoptopenjdk_11.version }}
  args:
    executable: /bin/bash
