---
- name: Download SDKMAN! installation script
  get_url:
    url: https://get.sdkman.io
    dest: /tmp/install_sdkman.sh
    mode: u+x

- name: Install SDKMAN!
  command: /tmp/install_sdkman.sh

- name: Use local SDKMAN! configurations by default
  lineinfile:
    path: ~/.sdkman/etc/config
    regexp: (sdkman_auto_env=)false
    line: '\1true'
    backrefs: yes

- name: Install JDK 8 ({{ sdkman.adoptopenjdk_8.version }})
  shell: . ~/.sdkman/bin/sdkman-init.sh && sdk install java {{ sdkman.adoptopenjdk_8.version }}
  args:
    executable: /bin/bash
  register: result
  failed_when:
    - result.rc != 0
    - '"is already installed" not in result.stdout'

- name: Install JDK 11 ({{ sdkman.adoptopenjdk_11.version }})
  shell: . ~/.sdkman/bin/sdkman-init.sh && sdk install java {{ sdkman.adoptopenjdk_11.version }}
  args:
    executable: /bin/bash
  register: result
  failed_when:
    - result.rc != 0
    - '"is already installed" not in result.stdout'

- name: Set up default JDK to 11 ({{ sdkman.adoptopenjdk_11.version }})
  shell: . ~/.sdkman/bin/sdkman-init.sh && sdk default java {{ sdkman.adoptopenjdk_11.version }}
  args:
    executable: /bin/bash
