---
- name: Install classic snaps
  snap:
    name: "{{ item }}"
    classic: yes
  with_items:
      - aws-cli
      - go

- name: Install non-classic snaps
  snap:
    name:
      - teams-for-linux

- import_tasks: teams.yml