---
- name: Check if teams-for-linux has permissions to use cameras
  shell: >
    set -o pipefail && \
    snap connections teams-for-linux | grep -e :camera.*:camera
  register: permissions_result
  changed_when: False
  failed_when: permissions_result == 2
  args:
    executable: /bin/bash

- name: Allow teams to use webcam
  command: snap connect teams-for-linux:camera core:camera
  when: permissions_result.rc != 0