---
- name: Download Terraform {{ terraform11.version }}
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform11.version }}/terraform_{{ terraform11.version }}_linux_amd64.zip
    dest: /tmp/

- name: Unarchive Terraform {{ terraform11.version }}
  unarchive:
    src: /tmp/terraform_{{ terraform11.version }}_linux_amd64.zip
    dest: ~/.local/bin/
    creates: ~/.local/bin/terraform
    mode: u+x
