---
- name: Check if terraform {{ terraform11.version }} is already installed
  stat:
    path: ~/.local/bin/terraform
  register: terraform_11
  become: no

- name: Installing terraform {{ terraform11.version }}
  import_tasks: terraform11.yml
  become: no
  when: not terraform_11.stat.exists

- name: Check if terraform {{ terraform12.version }} is already installed
  stat:
    path: ~/.local/bin/terraform12
  register: terraform_12
  become: no

- name: Installing terraform {{ terraform12.version }}
  import_tasks: terraform12.yml
  become: no
  when: not terraform_12.stat.exists

- name: Check if terraform {{ terraform13.version }} is already installed
  stat:
    path: ~/.local/bin/terraform13
  register: terraform_13
  become: no

- name: Installing terraform {{ terraform13.version }}
  import_tasks: terraform13.yml
  become: no
  when: not terraform_13.stat.exists

- name: Create Terraform's plugin cache folder
  file:
    path: ~/.terraform.d/plugin-cache
    state: directory

- name: Set up Terraform's plugin caching
  lineinfile:
    path: ~/.bashrc
    line: "export TF_PLUGIN_CACHE_DIR='~/.terraform.d/plugin-cache'"
