---
- name: Check if asdf is already installed
  stat:
    path: ~/.asdf
  register: asdf_folder

- name: Download asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: "{{ asdf.version }}"
  when: not asdf_folder.stat.exists

- name: Check if asdf fish completions need to be set up
  stat:
    path: ~/.config/fish/completions/asdf.fish
  register: completions

- name: Set up asdf fish completions
  command: cp ~/.asdf/completions/asdf.fish ~/.config/fish/completions
  when: not completions.stat.exists

- name: Add asdf to config.fish
  lineinfile:
    path: ~/.config/fish/config.fish
    line: "source ~/.asdf/asdf.fish"
    create: yes

- name: Add asdf to bashrc
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK (asdf)"
    block: |
      . ~/.asdf/asdf.sh
      . ~/.asdf/completions/asdf.bash

- name: Install asdf applications
  include_role:
    name: asdf
    apply:
      environment:
        PATH: "{{ ansible_env.PATH }}:~/.asdf/bin/"
  vars:
    asdf_plugin: "{{ item.plugin }}"
    asdf_version_prefix: "{{ item.version_prefix }}"
    asdf_set_default_version: "{{ item.set_default_version }}"
  loop:
    - { plugin: java, version_prefix: temurin-11, set_default_version: false }
    - { plugin: java, version_prefix: temurin-17, set_default_version: true }
    - { plugin: nodejs, version_prefix: 16, set_default_version: true }
