---
- name: Install docker.io
  apt:
    name: docker.io
    force_apt_get: yes

- name: Create docker group
  group:
    name: docker

- name: Allow running Docker without sudo
  user:
    name: "{{ calling_user }}"
    groups: docker
    append: yes

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: Create ~/.docker/cli-plugins directory if missing
  file:
    path: ~/.docker/cli-plugins
    state: directory
    recurse: yes
  become: no

- name: Download Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose.version }}/docker-compose-Linux-x86_64
    dest: ~/.docker/cli-plugins/docker-compose
    mode: u+x
  become: no
