---
- name: Set current user's default shell to fish
  user:
    name: "{{ calling_user }}"
    shell: /usr/bin/fish
  become: yes

- name: Create fish directory if missing
  file:
    path: ~/.config/fish
    state: directory

- name: Create fish completions directory if missing
  file:
    path: ~/.config/fish/completions
    state: directory

- name: Create fish functions directory if missing
  file:
    path: ~/.config/fish/functions
    state: directory

- name: Copy fish fzf key bindings
  copy:
    src: "{{ role_path }}/files/fish/plugins/fish_user_key_bindings.fish"
    dest: ~/.config/fish/functions/
    mode: 0664
