---
- name: Create Visual Studio Code's configuration folder if it's missing
  file:
    path: ~/.config/Code/User
    state: directory

- name: Import Visual Studio Code's configuration
  get_url:
    url: '{{ visual_studio_code.config }}'
    dest: ~/.config/Code/User/settings.json
    force: yes