---
- name: Install apt packages
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
  vars:
    packages:
    - ansible-lint
    - curl
    - openjdk-14-jdk
    - openjdk-14-doc
    - openjdk-13-jdk
    - openjdk-13-doc
