---
- name: Download asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: v{{ asdf.version }}

- name: Add asdf config to .bashrc
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK (asdf)"
    block: |
      . ~/.asdf/asdf.sh
      . ~/.asdf/completions/asdf.bash
