---
- name: Download JetBrains Toolbox
  get_url:
    url: https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ jetbrains_toolbox.version }}.tar.gz
    dest: /tmp/

- name: Unarchive JetBrains Toolbox
  unarchive:
    src: /tmp/jetbrains-toolbox-{{ jetbrains_toolbox.version }}.tar.gz
    dest: /tmp

- name: Copy JetBrains Toolbox to home directory
  copy:
    src: /tmp/jetbrains-toolbox-{{ jetbrains_toolbox.version }}/
    dest: ~/.local/bin/
    mode: u+x
