name: CI
on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run ansible-lint
      uses: ansible/ansible-lint-action@v4.1.0
      with:
        targets: playbook.yml
        args: -p
