name: CI
on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run ansible-lint
      uses: ansible/ansible-lint-action@master
